### ISSUE TITLE
Cleaning submissions

### ISSUE THREAD

**Issue by C1ares** [Ceylo/FurAffinityApp#3]
Hey, love the app! Makes using FA on the phone much less painful

Unfortunately though, I'm one of those people who like to not reach the highest possible numbers in the menubar, so after checking new submissions, I usually nuke them all

If there's no fundamental challenge in achieving this, I'd appreciate it a lot if you could look into adding this feature ^-^

**Comment by Ceylo** [comment]
Hey @C1ares !

I used to do the same until mainly using this app so I can totally understand.

There's no major issue in doing this, I just avoided this kind of action till now since it's destructive and I wouldn't want the app to mess up a user's data.

How do you expect this to behave?
- New submissions automatically cleaned up from your account after getting fetched by the app? Could work but you wouldn't be able to check them later on the website, also the app doesn't save (although it could be changed) in a persistent way the list of submissions, so if it gets killed/crashes/you restart your device, then you'd have lost your submission feed.
- Manual removal: like Apple Mail app let's say, you can manually swipe one to remove it or Edit, Select all then delete. Might be a bit tricky to implement correctly since the feed is just based on the first 72 submissions listed on your account. So this "delete all" would only delete at most 72 items.
- Just give access to Nuke All Submissions button from the app. Simple to implement. To make things consistent your feed in the app would then become empty.

**Comment by C1ares** [comment]
Hi @Ceylo, thank you for the swift response!

Personally, a simple button to clear all submissions at the very bottom of the feed would work best, since I never had to keep any after I've viewed them

**Comment by Ceylo** [comment]
@C1ares this is coming in next release :)

https://user-images.githubusercontent.com/451334/212569179-4d519c5c-e781-42cb-b66f-5527bf6ebda4.mov

**Comment by C1ares** [comment]
> @C1ares this is coming in next release :)
> 
>  nuke.mov

Looks great, thank you so much ^~^

**Comment by Ceylo** [comment]
Fixed in [version 1.5.0](https://github.com/Ceylo/FurAffinityApp/releases/tag/1.5.0) of the app.
