### ISSUE TITLE
[Bug] unable to open galleries of profiles while the app is hidden iOS 18

### ISSUE THREAD

**Issue by ericgryffindor** [Ceylo/FurAffinityApp#7]
when the App is hidden and locked with Face ID in iOS 18 the gallery and scraps of user profiles seem unable to be opened . when only locked with face id it behaves normally

**Comment by Ceylo** [comment]
Hi @ericgryffindor,
Thanks for providing this feedback.
At the moment I don't have a device with iOS 18 to test and fix this, and since I only have a personal iPhone, I don't plan to upgrade before it gets more stable with iOS 18.1 or 18.2. Additionally, development tools don't look to allow simulating the lock & hide feature. Hopefully as I understand this is not critical and you should just not hide the app until it's fixed.

**Comment by Ceylo** [comment]
Hello @ericgryffindor,

I looked into this. I can reproduce the issue but I don't have any good solution.
[Other apps are affected](https://forums.developer.apple.com/forums/thread/763107) differently but for the same technical reason, and I think this is inherent to this lock and hide feature.

For the gory technical details:
The FA app uses special links (URLs starting with `furaffinity-app-navigation://`) to mimic FA website structure. For instance https://www.furaffinity.net/view/1234 can be opened in the app with `furaffinity-app-navigation://www.furaffinity.net/view/1234`. When FA users share text with links (in comments, submissions, journals and user descriptions), the links are converted to this `furaffinity-app-navigation://` scheme. The FA app has told iOS that it can handle this kind of link, meaning that they should open in the FA app. Thanks to this, the app can keep rendering blocks of HTML (taken from FA website) in the app, to preserve formatting, font, colors, etc. If the links were not converted, then tapping them would open your web browser instead of continuing inside of the app.

However, when you choose to hide the app, iOS assumes that you don't want to reveal that you have this app. So although it knows that these links should be opened in the FA app, it won't, in order to preserve your privacy. The stupid part is that you're already in the app, so in the current case, iOS would not reveal the app if it actually opened these links. But it doesn't look to handle this corner case, and thus nothing happens in the app.

I could _maybe_ change some of the links inside the app, like the controls on user page. But links from text blocks would stay broken. And I don't like spending time to still end-up with a half broken application.

So… for the foreseeable future, I can only say that the FA app is not compatible with iOS's lock and hide feature. You may only lock.

**Comment by Ceylo** [comment]
No reasonable solution and not a blocking issue so no fix is planned

**Comment by Ceylo** [comment]
@ericgryffindor In case you're still interested in this, I found a way around this issue (basically in-app navigation without using the special URL scheme in submissions descriptions). So this will be resolved in upcoming 1.19 release.
